config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
resources :users do
resources :albums do
resources :photos do
  resources :sharings, only: [:new, :create, :destroy]
end
end
end
resources :tags
resources :sharings do
  resources :comments
  resources :likes, only: [:new, :create, :destroy] do
    member do
        get 'id'
    end
  end
end
root to: 'albums#index'

end

app/models/album.rb
class Album < ActiveRecord::Base
has_many :photos, :dependent => :destroy
belongs_to :user
validates :name, presence: true
end
 

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
def index
	@user=User.find(current_user.id)
	@albums=@user.albums.all
	#byebug
	# @cover=Photo.where(params[:album_id] => f.id).first

end
def new
	@user=User.find(current_user.id)
	@album=@user.albums.build
end
def create
	@user=User.find(current_user.id)
	@album=@user.albums.build(album_params)
	if @album.save
		redirect_to '/'
	else
		render 'new'
	end
end
def show
	@user=User.find(params[:user_id])
	@album=@user.albums.find(params[:id])
	@images=@album.photos.paginate(page: params[:page], per_page: 4)
	respond_to do |format|
    format.html
    format.json { render json: @images }
    format.js
  				end

end
def edit
	@user=User.find(params[:user_id])
	@album=@user.albums.find(params[:id])
end
def update
	@user=User.find(current_user)
	@album=@user.albums.find(params[:id])
	if @album.update(album_params)
		redirect_to '/'
	else
		render 'edit'
	end
end
def destroy
	@user=User.find(current_user)
	@album=@user.albums.find(params[:id])
	@album.destroy
		 respond_to do |format|
      format.html { redirect_to '/' }
      format.json
      format.js   { render :layout => false }
    end
		
	
end

def cover_image(id)

return @cover
end

private
def album_params
	params.require(:album).permit(:name)
end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/_albums.html.erb
<% @albums.each do |f| %>
<!-- <p class="well">name count is <%=f.name.length %></p> -->
<div class="col-xs-6 col-md-3 album">
		<div class="thumbnail rotate" id="photo_back">
		<% if f.photos.present? %>
		<td id="ex5"><%= link_to image_tag(f.photos.first.snaps_url(:medium)), user_album_path(@user.id,f.id)%> </td>
		<%else%>
			<td><%=link_to image_tag("water.jpg"), user_album_path(@user.id,f.id) %>
			</td>
		<%end%>
			 <div class="caption">
			<h3 ><a href="<%= user_album_path(@user.id,f.id) %>" class="btn btn-success btn-lg btn-block"><i class="glyphicon glyphicon-picture"></i> <%= f.name %>    <span class="badge"><%= f.photos.count %></span></a></h3>


			<div class="btn-group btn-group-justified" role="group">
			<div class="btn-group" role="group">
			<%= link_to edit_user_album_path(@user.id,f.id), remote: true, class: "btn btn-warning btn-xs" do %>
                        <i class="glyphicon glyphicon-pencil"></i> Edit
                        <%end%>
                        </div>
							<div class="btn-group">
							<%= link_to user_album_path(@user.id,f.id), :method => :delete, data: { confirm: "Are You Sure?"}, remote: true, class: "btn btn-danger btn-xs delete_album" do %>
                        <i class="glyphicon glyphicon-trash"></i> Delete
                        <%end%>
							</div>

			</div>
			</div>
		</div>
</div>
				<%end%>

app/views/albums/_edit.html.erb
<div class="modal-dialog">
<div class="jumbotron" id="home">
<h3>Edit Album</h3>
  <div class="modal-content">

<p>
<%=form_for :album, :url => user_album_path, :method => :put do |f| %>
<div class="modal-body">
<div class="input-group">
<%= f.text_field :name, placeholder: "Album Name", class: "form-control" %></div><br>
<div class="modal-footer">
	<div class="btn-group btn-group-justified" role="group">
	<div class="btn-group" role="group">
	<%= f.submit :submit, class: "btn btn-success btn-lg"%>
	</div>
	<div class="btn-group">
	<%= link_to "Cancel", :back, class: "btn btn-warning btn-lg"%>
	</div>
	</div>
</div>
</div>
<%end%>
</p>
</div>
</div>
</div>
</div>

app/views/albums/_new.html.erb
<%=form_for :album, :url => user_albums_path, :method => :post do |f| %>

<div class= "input-group">
<%= f.text_field :name, placeholder: "Enter Album Name", class: "form-control"%></div><br>

							<div class="btn-group btn-group-justified" role="group">
							<div class="btn-group" role="group">
		<%= f.submit :submit, remote: true, class: "btn btn-success btn-md add_album"%>
							</div>
							<div class="btn-group">
		<%= link_to "Cancel", :back, class: "btn btn-warning btn-md"%>
							</div>

							</div>


<%end%>

app/views/albums/_pages.html.erb
<% if (@images.count)%4 != 0 %>
<% pages= (@images.count/4)+1 %>
<%else%>
<% pages= (@images.count/4) %>
<%end%>
<center>
<ul class="pagination">

<% if @images.current_page == 1 %>
<li class="disabled"><a href="/users/<%= current_user.id %>/albums/<%= @album.id %>?page=1"> First</a></li>
<%else%>
<li id="home-page" class="active"><a href="/users/<%= current_user.id %>/albums/<%= @album.id %>?page=1"> First</a></li>
<%end%>

<% if @images.current_page - 1 > 0 %>
<li><a href="/users/<%= current_user.id %>/albums/<%= @album.id %>?page=<%= @images.current_page - 1 %>"> Previous</a></li>
<%else%>
<li class="disabled"><a href="/users/<%= current_user.id %>/albums/<%= @album.id %>?page=<%= @images.current_page - 1 %>"> Previous</a></li>
<%end%>

<% for i in 1..pages do %>

    <li><a href="/users/<%= current_user.id %>/albums/<%= @album.id %>?page=<%= i %>"> <%= i %></a></li>

<%end%>
<% if @images.current_page + 1 <= pages %>
<li><a href="/users/<%= current_user.id %>/albums/<%= @album.id %>?page=<%= @images.current_page + 1 %>"> Next</a></li>
<%else%>
<li class="disabled"><a href="/users/<%= current_user.id %>/albums/<%= @album.id %>?page=<%= @images.current_page %>"> Next</a></li>
<%end%>

<% if @images.current_page == pages %>
<li class="disabled"><a href="/users/<%= current_user.id %>/albums/<%= @album.id %>?page=<%= pages %>"> Last</a></li>
<%else%>
<li id="home-page" class="active"><a href="/users/<%= current_user.id %>/albums/<%= @album.id %>?page=<%= pages %>"> Last</a></li>
<%end%>

</ul>
</center>

app/views/albums/_photos.html.erb
<% @images.each do|f| %>
	<div class="col-xs-6 col-md-3">
    <div class="thumbnail tilt" id="photo_back">
    

    <!---Sharing Feature Button-->
<div class="share">
<% if f.sharings.present? %>
<% @sharings=f.sharings %>
<% @sharings.each do |t| %>
	<%=link_to user_album_photo_sharing_path(@user.id,@album.id, f.id, t.id), :method => :delete, class: "btn btn-warning" do %>
                                                                    <i class="glyphicon glyphicon-ban-circle"></i> UnShare
                                                                    <%end%>
<%end%>
<%else%>
	<%=link_to new_user_album_photo_sharing_path(@user.id,@album.id, f.id), class: "btn btn-warning" do %>
                                                                    <i class="glyphicon glyphicon-share"></i> Share
                                                                    <%end%>
<%end%>
</div>


<!---Sharing Feature Button End-->


	<% if /missing.png/.match(f.snaps_url) %>
	<%else%>
	<%= link_to image_tag(f.snaps_url(:medium)), f.snaps_url%>
	<% @tags=f.tags %>
	<div class="caption">
	
	<h2>
<% if f.title.length > 13 %>
	<b id="txt"><%= f.title[0...10]+".." %></b>
<%else%>
	<b id="txt"><%= f.title %></b>
<%end%>
	</h2>
	<span  id="txt">Tags: </span>
	<% @tags.each do |t| %>
		<span><%= link_to tags_path, class: "btn btn-info btn-xs" do %>
                                                                    <i class="glyphicon glyphicon-tag"></i> <%= t.tname %>
                                                                    <%end%></span> 
		<%end%><br><br>








<div class="btn-group btn-group-justified" role="group">
<div class="btn-group" role="group">
<%=link_to edit_user_album_photo_path(@user.id,@album.id, f.id), class: "btn btn-success" do %>
                                                                    <i class="glyphicon glyphicon-pencil"></i> Edit
                                                                    <%end%>
</div>
<div class="btn-group" role="group">
<%= link_to user_album_photo_path(@user.id,@album.id,f.id), :method => "delete", data: { confirm: "Are You Sure?"}, class: "btn btn-danger" do %>
                                                                    <i class="glyphicon glyphicon-trash"></i> Delete
                                                                    <%end%>
</div>
</div>
</div>
</div>
<%end%></div>
	<%end%>

app/views/albums/create.js.erb
$('.add_album').bind('ajax:success', function() {  
      $(this).closest('.album').fadein();
});

app/views/albums/destroy.js.erb
$('.delete_album').bind('ajax:success', function() {  
        $(this).closest('.album').fadeOut();
});

app/views/albums/edit.js.erb
$("#album-modal").html("<%= escape_javascript(render 'edit') %>")
$("#album-modal").modal("show")

app/views/albums/index.html.erb
<div class="container">


</div>

<div class="container">

<div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <div class="jumbotron" id="home2">
					<h1>Welcome, <span class="pull-right"> <%= link_to image_tag(current_user.avatar_url),"#", class: "img-circle" %>
					 <%=current_user.username %></span></h1>
					</div>
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
      <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">

      <div class="item active">
      <%=link_to image_tag("spring-time.jpg"), '#Home', class: "frame" %>
        <div class="carousel-caption">
          <h3>Ansel Adams</h3>
          <p>"When words become unclear, I shall focus with photographs. When images become inadequate, I shall be content with silence."</p>
        </div>
      </div>

      <div class="item">
        <%=link_to image_tag("clock.jpg"), '#Home', class: "frame" %>
        <div class="carousel-caption">
          <h3>Hselmak</h3>
          <p>"Capture the moment now or else its gone forever, just leaving behind the tained memmories with the happiness."</p>
        </div>
      </div>
    
      <div class="item">
        <%=link_to image_tag("alone.jpg"), '#Home', class: "frame" %>
        <div class="carousel-caption">
          <h3>Leonardo</h3>
          <p>"Even the silence says the thousand words, a picture can show the thousand emotions of the moments that has been lived and still feels alive somewhere."</p>
        </div>
      </div>

      <div class="item">
        <%=link_to image_tag("family.jpg"), '#Home', class: "frame" %>
        <div class="carousel-caption">
          <h3>Happiness forever.....</h3>
          <p>"Everytime you can't be happy, but the glimse of the happiness of all the time will always be right in front of you always."</p>
        </div>
      </div>
  
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>
<br>

















<div class="container" id="main-content">
					<div class="jumbotron visible-lg-* lg-home" id="home">
					
					  <center>
					  <p  id="new"> <b>Create a</b><br>
					<%= link_to new_user_album_path(@user), remote: true, class: "btn btn-primary btn-lg", role: "button" do%>
					<i class="glyphicon glyphicon-camera"> New Album</i><%end%>
					<div id="album-modal" class="modal fade"></div>
					  </p>


					  <div class="col-sm-3" id="add"></div>	</center>
					</div>


				
<% if @albums.present? %>

<div class="row index-line" id="all-albs">

				<%= render 'albums' %>
				
				</div>
<%else%>
<center>
<div class="row no-pic-line" id="no-albs">
<h1>NO Albums</h1>

</div>
</center>
<%end%>
</div>

app/views/albums/new.js.erb
// $("#album-modal").html("<%= escape_javascript(render 'new') %>")
// $("#album-modal").modal("show")

$('#add').html("<%= escape_javascript(render 'new') %>");
// $('#new').remove().fadeOut();

$('#new').addClass('hidden');

app/views/albums/show.html.erb
<div class="container">

<div class="jumbotron" id="home">
<h1 class="text-success"><%= @album.name %>  <span class="label label-default"><%= @images.count %></h1>
<p>
<%= link_to new_user_album_photo_path(@user.id,@album.id),  class: "btn btn-primary btn-lg pull-right", role: "button" do %>
					    <i class="glyphicon glyphicon-plus"></i> Photo
					    <%end%><br></p>
</div>


<ol class="breadcrumb">
  <li><a href="<%= user_albums_path %>">Home</a></li>
  <li class="active"><%= @album.name %></li>
</ol>

<% if @images.present? %>
<div class="row line" id="photo-listings">
<!--Photo Listings-->
<%= render "photos" %>
</div>



<!--Pagination Setup-->
<% if @images.count <= 4 %>
<div id="pages-listing" class="hidden">
<%= render "pages" %>
</div>
<%else%>
<div id="pages-listing">
<%= render "pages" %>
</div>
<%end%>

<%else%>
<div class="row no-line">
<center>
<h1> <%= link_to new_user_album_photo_path(@user.id,@album.id),  class: "btn btn-warning btn-lg" do %>
					    <i class="glyphicon glyphicon-plus"></i> Photo
					    <%end%> </h1>
					    </center>
</div>
<!--filling-->
<div class="col-md-12"><br><br></div>
<%end%>

</div><!--Ending of the container-->
<script>
$(function(){
	
   $('.pagination a').attr('data-remote', 'true');
});


</script>

app/views/albums/show.js.erb
$("#photo-listings").html("<%= escape_javascript(render 'photos') %>");
$("#pages-listing").html("<%= escape_javascript(render 'pages') %>");
$('.pagination a').attr('data-remote', 'true');