config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
resources :users do
resources :albums do
resources :photos do
  resources :sharings, only: [:new, :create, :destroy]
end
end
end
resources :tags
resources :sharings do
  resources :comments
  resources :likes, only: [:new, :create, :destroy] do
    member do
        get 'id'
    end
  end
end
root to: 'albums#index'

end

app/models/photo.rb
class Photo < ActiveRecord::Base

mount_uploader :snaps, SnapsUploader
has_and_belongs_to_many :tags, :dependent => :destroy
has_and_belongs_to_many :sharings, :dependent => :destroy
belongs_to :album
attr_accessor :tags_attributes
#attr_accessor :split_tags
#accepts_nested_attributes_for :tags
validates :snaps, presence: true
after_save :split_tags

#before_save :tag_split
private
def split_tags
	@user_id=self.album.user_id
	#debugger
	if @tags_attributes
	self.tags=@tags_attributes.split(",").map do |name|
				Tag.where(tname: name).first_or_create(:tname => name, :user_id => @user_id)
		end
end
end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
#before_filter :set_tags_attribute
def new
	@user=User.find(params[:user_id])
	@album=@user.albums.find(params[:album_id])
	@photo=@album.photos.build
	@tags=Tag.new
	#@tags.tname = ['','','']

end
def create
	@user=User.find(params[:user_id])
	@album=@user.albums.find(params[:album_id])
	@photo=@album.photos.build(photo_params)
		if @photo.save
			#debugger
			
			flash[:success]="The photo and tags was added!"
		redirect_to user_album_path(@user.id,@album.id)
	else
		render 'new'
	end
end
def edit
	@album=Album.find(params[:album_id])
	@photo=Photo.find(params[:id])
end
def update
	@album=Album.find(params[:album_id])
	@photo=Photo.find(params[:id])
	
	if @photo.update(photo_params)
		flash[:success]="The photo was updated!"
		redirect_to user_album_path(current_user, @album)
	else
		render 'edit'
	end
end
def destroy
	@album=Album.find(params[:album_id])
	@photo=Photo.find(params[:id])
	@photo.destroy
	flash[:success]="The photo was destroyed."
	redirect_to user_album_path(current_user.id, @album.id)
end
private
def photo_params
	params.require(:photo).permit(:snaps,:title,:tags_attributes)
end
# def tag_params
# 	params.require(:tags).permit(:tname)
# end
# def set_tags_attribute
# 	@photo.tags_attributes = params[:tname]
# end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/edit.html.erb
<div class="container">
<% #debugger%>

<div class="jumbotron" id="home">
<h1><%= @album.name %></h1>
<p>Edit Photo</p>

</div>
<div style="float: left; padding-left: 2em" class="tilt">

<img src="<%= @photo.snaps_url(:small) %>" alt="old image">


</div>
 <div class="forms_right">
  <!-- Default panel contents -->
  
<%= form_for :photo, :url => user_album_photo_path, :method => 'put' do |f| %>
	<div class="input-group input-width">	
	<%= f.text_field :title, placeholder: 'Title', class: "form-control" %></div>
<br>
	<p class="input-group"><b>Attach photo</b> 
	<%= f.file_field :snaps, class: "btn btn-default btn-sm input-width" %><br>
		<%= f.text_field :tags_attributes, placeholder: "Tags", class: "form-control input-width" %><%#end%></p>
		<br>
			<div class="btn-group btn-group-justified" role="group">
			<div class="btn-group" role="group">
			<%= f.submit :submit, class: "btn btn-success btn-sm"%>
			</div>
			<div class="btn-group">
			<%= link_to "Cancel", :back, class: "btn btn-warning btn-sm"%>
			</div>

			</div>
	<%end%>
	
	</div>
	</div>

app/views/photos/new.html.erb
<div class="container">
<ol class="breadcrumb">
  <li><a href="<%= user_albums_path %>">Home</a></li>
  <li><a href="<%= user_album_path(@user.id,@album.id) %>"><%= @album.name %></a></li>
  <li class="active">Add Photo</li>
</ol>
<div class="jumbotron" id="home">
<h1><%= @album.name %></h1>
<p>ADD PHOTO</p>

</div>

  <div class="forms_right">
<%= form_for :photo, :url => user_album_photos_path, :method => :post, :html => { :multipart => true } do |f| %>
<div class="input-group input-width">	
	<%= f.text_field :title, placeholder: 'Title', class: "form-control" %>
</div>
<br>
<p class="input-group"><b>Attach photo</b> 
<%= f.file_field :snaps, class: "btn btn-default btn-sm input-width" %>
<br>
		<%= f.text_field :tags_attributes, placeholder: "Tags", class: "form-control input-width" %><%#end%></p>
				<br>
						<div class="btn-group btn-group-justified" role="group">
							<div class="btn-group" role="group">
							<%= f.submit "Submit", class: "btn btn-success btn-sm add_photo"%>
							</div>
							<div class="btn-group">
							<%= link_to "Cancel", :back, class: "btn btn-warning btn-sm"%>
							</div>
						</div>
	<%end%>
	</div>


</div>