config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
resources :users do
resources :albums do
resources :photos do
  resources :sharings, only: [:new, :create, :destroy]
end
end
end
resources :tags
resources :sharings do
  resources :comments
  resources :likes, only: [:new, :create, :destroy] do
    member do
        get 'id'
    end
  end
end
root to: 'albums#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>K-Album</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
   <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
<link href='https://fonts.googleapis.com/css?family=Roboto|Open+Sans+Condensed:300|Oxygen|Maven+Pro|Pacifico' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Roboto|Oswald|Quicksand:700|Quattrocento+Sans|Ruda|Allerta+Stencil|Monoton|Iceland|Sarpanch' rel='stylesheet' type='text/css'>

<link href='https://fonts.googleapis.com/css?family=Poiret+One|Indie+Flower|Inconsolata|Architects+Daughter' rel='stylesheet' type='text/css'>

<link href='https://fonts.googleapis.com/css?family=Indie+Flower|Shadows+Into+Light|Dancing+Script' rel='stylesheet' type='text/css'>

  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation" id="nav">
  <div class="navbar-inner">
  <div class="container">
 
  <% if current_user %>
  <div class="navbar-header">
  <button type="button" class="navbar-toggle" data-toggle="collapse" 
         data-target=".navbar-collapse">
         <span class="sr-only">Toggle navigation</span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand pull-left"><strong>KALBUM</strong> </span>
      </div>
   
 

                <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
<% if params[:action]=="index" %>
            <% if params[:controller]=="albums"%>
                        <li class="active"><%= link_to user_albums_path(current_user.id) do%>
                        <strong>HOME</strong> <i class="glyphicon glyphicon-home"></i>
                        <%end%>
                        </li>
                        <li id="btn-back"><%= link_to tags_path, id: "txt" do%>
                        <span>TAGS</span> <i class="glyphicon glyphicon-tags"></i>
                        <%end%>
                        </li>
                        <li id="btn-back"><%= link_to sharings_path, id: "txt" do%>
                        <span>BROADCASTS</span> <i class="fa fa-bullhorn fa-lg"></i>
                        <%end%>
                        </li>
                        <li id="btn-back"><a data-toggle="modal" href="#HELP" id="txt">Help <i class="fa fa-question fa-lg"></i></a></li>
            <%else%>
                <% if params[:controller]=="tags"%>
                        <li id="btn-back"><%= link_to user_albums_path(current_user.id), id: "txt" do%>
                        <span>HOME</span> <i class="glyphicon glyphicon-home"></i>
                        <%end%>
                        </li>
                        <li class="active"><%= link_to tags_path, id: "txt" do%>
                        <strong>TAGS</strong> <i class="glyphicon glyphicon-tags"></i>
                        <%end%>
                        </li>  
                        <li id="btn-back"><%= link_to sharings_path, id: "txt" do%>
                        <span>BROADCASTS</span> <i class="fa fa-bullhorn fa-lg"></i>
                        <%end%>
                        </li>
                        <li id="btn-back"><a data-toggle="modal" href="#HELP" id="txt">Help <i class="fa fa-question fa-lg"></i></a></li>
                <%else%>
                        <li id="btn-back"><%= link_to user_albums_path(current_user.id), id: "txt" do%>
                        <span>HOME</span> <i class="glyphicon glyphicon-home"></i>
                        <%end%>
                        </li>
                        <li id="btn-back"><%= link_to tags_path, id: "txt" do%>
                        <span>TAGS</span> <i class="glyphicon glyphicon-tags"></i>
                        <%end%>
                        </li>
                        <li class="active"><%= link_to sharings_path, id: "txt" do%>
                        <strong>BROADCASTS</strong> <i class="fa fa-bullhorn fa-lg"></i>
                        <%end%>
                        </li>
                        <li id="btn-back"><a data-toggle="modal" href="#HELP" id="txt">Help <i class="fa fa-question fa-lg"></i></a></li>
                <%end%>
            <%end%>
<%else%>
    <li id="btn-back"><%= link_to user_albums_path(current_user.id), id: "txt" do%>
    <span>HOME</span> <i class="glyphicon glyphicon-home"></i>
    <%end%>
    </li>
    <li id="btn-back"><%= link_to tags_path, id: "txt" do%>
    <span>TAGS</span> <i class="glyphicon glyphicon-tags"></i>
    <%end%>
    </li>
    <li id="btn-back"><%= link_to sharings_path, id: "txt" do%>
    <span>BROADCASTS</span> <i class="fa fa-bullhorn fa-lg"></i>
    <%end%>
    </li>
    <li id="btn-back"><a data-toggle="modal" href="#HELP" id="txt">Help <i class="fa fa-question fa-lg"></i></a></li>
<%end%>
                </ul>
                      

<ul class="nav navbar-nav navbar-right">

    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown"> <%= image_tag current_user.avatar_url, class: "img-small" %> <span id="txt"><%= current_user.email %></span> <span class="caret"></span></a>
         <ul class="dropdown-menu">
          
          <li>
          <%= link_to edit_user_registration_path do %>
            <i class="fa fa-cogs fa-lg"> C</i>hange Settings
            <%end%>
          </li>
          <li role="separator" class="divider"></li>
          <li>
          <%= link_to user_registration_path, data: { confirm: "Are you sure?" }, method: :delete do %>
            <i class="fa fa-times fa-lg"> D</i>elete Account
            <%end%>
          </li>
          <li>
            
            <%= link_to destroy_user_session_path, :method => :delete  do %>
            <i class="fa fa-lock fa-lg"> L</i>ogout
            <%end%>
          </li>

          <li role="separator" class="divider"></li>
          <li><a data-toggle="modal" href="#ABOUT"><i class="fa fa-info-circle fa-lg"> A</i>
bout</a></li>
          </ul>
    </li>
</ul>











                </div>
 <% else %>
          <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" 
         data-target=".navbar-collapse">
         <span class="sr-only">Toggle navigation</span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand pull-left">KALBUM</span>
          </div>
              <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav pull-right">
                <%= link_to new_user_session_path, class: "btn btn-primary navbar-btn btn-md", role: "button" do%>
                <i class="fa fa-user fa-lg"> Login</i><%end%>

                <span>  <b>OR</b>  </span>
                <%= link_to new_user_registration_path, class: "btn btn-warning navbar-btn btn-md", role: "button" do%>
                <i class="fa fa-user-plus fa-lg"> Signup</i><%end%>
                
                </ul>
              </div>
  <%end%>
</div>
</div>
</nav>

</head>


<!-- HELP Modal -->
<div id="HELP" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header alert alert-warning">
      <h2>
      <%=link_to image_tag("chrome.png"), 'https://www.google.com/chrome/', title: 'Google Chrome', rel: 'tooltip' , class: "medium-logo" %>
        Best viewed in Chrome.
        </h2>
      </div>
      <div class="modal-body">
        <p class="well">
        
        <strong>KALBUM HELP?</strong>
        <ul>
        <li>Viewing issue</li>
        <p> <small>Experiencing any view related problem like "album seems large and all" kindly shift to chrome.</small></p>
        <li>Downloading</li>
        <p> <small>To Download a photo just click on the photo to open in full resolution, then right click and select "save as"</small></p>
        <li>Share</li>
        <p> <small>To share the photo kindly take the mouse to the upper left of the photo-card and the sharing button will be visible.</small></p>
        </ul>

        </p>
        
        <h3> For More On This</h3>
        <div class="col-md-6">
        <%=link_to image_tag("cloudinary.png"), 'http://cloudinary.com/', title: 'Cloudinary', rel: 'tooltip' , class: "logo" %>&nbsp
        <%=link_to image_tag("bootstrap.png"), 'http://getbootstrap.com/', title: 'Bootstrap', rel: 'tooltip' , class: "logo" %>&nbsp
        <%=link_to image_tag("js.png"), 'http://w3schools.com/js/', title: 'JavaScript', rel: 'tooltip' , class: "logo" %>&nbsp
        <%=link_to image_tag("jquery.png"), 'http://jquery.com/', title: 'Jquery', rel: 'tooltip' , class: "logo" %>&nbsp
        </div>
        <!--fillings-->
        &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
        &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
        <!--filling-->
       
        
        
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default btn-block" data-dismiss="modal">Close</button> 
      </div>
    </div>

  </div>
</div>





















 
<!-- About Modal -->
<div id="ABOUT" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        
        
      </div>
      <div class="modal-body">
        <p class="well">
        
        <strong>KALBUM</strong> is an Album gallery application. Backed with cloud thanks to the cloudinary an freely available cloud-storage for safe storage of the Images and provides authentication through Devise one of the widly used gem for authentication purposes in ruby. Apart from being just a private album gallery it allows you to share your memorable moments with others in the KALBUM.<br>
        So feel free to Upload, Download, Watch, Share, Comment and Like all that u want with KALBUM, speak your mind or share a photo. Open in a Mobile Or a Tablet Or maybe not try a PC choose what ever you want.

        </p>
        <p>
        <h3> For More On This</h3>
        <%=link_to image_tag("cloudinary.png"), 'http://cloudinary.com/', title: 'Cloudinary', rel: 'tooltip' , class: "logo" %>&nbsp
        <%=link_to image_tag("bootstrap.png"), 'http://getbootstrap.com/', title: 'Bootstrap', rel: 'tooltip' , class: "logo" %>&nbsp
        <%=link_to image_tag("js.png"), 'http://w3schools.com/js/', title: 'JavaScript', rel: 'tooltip' , class: "logo" %>&nbsp
        <%=link_to image_tag("jquery.png"), 'http://jquery.com/', title: 'Jquery', rel: 'tooltip' , class: "logo" %>&nbsp
        <!--fillings-->
        &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
        &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
        <!--filling-->
        <%=link_to image_tag("ror.png"), 'http://guides.rubyonrails.org/', title: 'Ruby On Rails', rel: 'tooltip', class: "medium-logo" %>
        </p>
        
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default btn-block" data-dismiss="modal">Close</button> 
      </div>
    </div>

  </div>
</div>


<body>

<%= yield %>

</body>
<nav class="navbar navbar-inverse navbar-static-bottom" id="bottom-nav">
  <div class="navbar-inner">
  <div class="container">
<div class="row">
<div class="navbar-text col-md-4 col-sm-4"><b>KALBUM<i class="glyphicon glyphicon-registration-mark"></i></b></div>
<div class=" navbar-btn col-md-4 col-sm-4">
<%=link_to image_tag("cloudinary.png"), 'http://cloudinary.com/', title: 'Cloudinary', rel: 'tooltip' , class: "logo" %>&nbsp
<%=link_to image_tag("bootstrap.png"), 'http://getbootstrap.com/', title: 'Bootstrap', rel: 'tooltip' , class: "logo" %>&nbsp
<%=link_to image_tag("js.png"), 'http://w3schools.com/js/', title: 'JavaScript', rel: 'tooltip' , class: "logo" %>&nbsp
<%=link_to image_tag("jquery.png"), 'http://jquery.com/', title: 'Jquery', rel: 'tooltip' , class: "logo" %>
</div>
<div class="navbar-text col-md-3 col-sm-3"><b>By Kamlesh Mehta</b></div>
  
</div>

  </div>

  </div>
  </nav>
</html>